[workspace]

[package]
name = "tuf_replay_server"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "tuf_replay_server-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
loco-rs = { version = "1.1" }

[features]
e2e = []

[dependencies]
loco-rs = { workspace = true , features = ["worker"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
json5 = "0.4"
tokio = { version = "1.45", default-features = false, features = ["fs", "io-util", "rt-multi-thread", "sync", "time"] }
async-trait = { version = "0.1" }
axum = { version = "0.8", features = ["ws"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
migration = { path = "migration" }
sea-orm = { version = "2.0", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
chrono = { version = "0.4" }
uuid = { version = "1.6", features = ["v4"] }
validator = { version = "0.20", features = ["derive"] }
base64 = { version = "0.22" }
getrandom = { version = "0.3" }
hex = { version = "0.4" }
redis = { version = "1", features = ["aio", "tokio-comp", "connection-manager"] }
sha2 = { version = "0.10" }
thiserror = { version = "2" }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "stream", "rustls"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
tempfile = "3.27.0"
bytes = "1.12.1"
unicode-normalization = "0.1.25"
tokio-util = { version = "0.7.19", features = ["io"] }
futures-util = "0.3"

[[bin]]
name = "tuf_replay_server-cli"
path = "src/bin/main.rs"
required-features = []

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
tokio-tungstenite = "0.29"
serial_test = { version = "3.1.1" }
rstest = { version = "0.25" }
insta = { version = "1.34", features = ["redactions", "yaml", "filters"] }
