#!/usr/bin/env bash

if [ "${TUFREPLAY_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
TUFREPLAY_CONTEXT_LOADED=1

TUFREPLAY_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TUFREPLAY_PROJECT_ROOT="$(cd "$TUFREPLAY_LIB_DIR/../.." && pwd)"

if [ -f "$TUFREPLAY_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$TUFREPLAY_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"

DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"

UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"
ADOFAI_IPC_DLL="${ADOFAI_IPC_DLL:-${ADOFIA_IPC_DLL:-$ADOFAI_MODS_DIR/AdofaiIpc/AdofaiIpc.dll}}"
ADOFAI_IPC_BOOTSTRAP_DLL="${ADOFAI_IPC_BOOTSTRAP_DLL:-$ADOFAI_MODS_DIR/AdofaiIpc/AdofaiIpc.Bootstrap.dll}"
ADOFAI_IPC_INFO_JSON="${ADOFAI_IPC_INFO_JSON:-$ADOFAI_MODS_DIR/AdofaiIpc/Info.json}"
ADOFAI_IPC_BOOTSTRAP_LOCK="$TUFREPLAY_PROJECT_ROOT/TUFReplay/AdofaiIpcBootstrap.lock"

TUFREPLAY_BUILD_OUTPUT="${TUFREPLAY_BUILD_DIR:-$TUFREPLAY_PROJECT_ROOT/build/TUFReplay}"
TUFREPLAY_BOOTSTRAP_BUILD_OUTPUT="${TUFREPLAY_BOOTSTRAP_BUILD_DIR:-$TUFREPLAY_PROJECT_ROOT/build/TUFReplay.Bootstrap}"
TUFREPLAY_INSTALL_PATH="${TUFREPLAY_INSTALL_DIR:-$ADOFAI_MODS_DIR/TUFReplay}"

TUFREPLAY_MAC_HELPER_BUILD_OUTPUT="${TUFREPLAY_MAC_HELPER_BUILD_DIR:-$TUFREPLAY_PROJECT_ROOT/build/macos-helper}"
TUFREPLAY_MAC_HELPER_DERIVED_DATA="$TUFREPLAY_MAC_HELPER_BUILD_OUTPUT/DerivedData"
TUFREPLAY_MAC_HELPER_BUILT_APP="$TUFREPLAY_MAC_HELPER_DERIVED_DATA/Build/Products/Release/TUFReplayMicrophoneCapture.app"
TUFREPLAY_MAC_HELPER_APP="$TUFREPLAY_MAC_HELPER_BUILD_OUTPUT/TUFReplayMicrophoneCapture.app"
TUFREPLAY_MAC_HELPER_EXECUTABLE="$TUFREPLAY_MAC_HELPER_APP/Contents/MacOS/TUFReplayMicrophoneCapture"
TUFREPLAY_MAC_HELPER_XCODE_PROJECT="$TUFREPLAY_PROJECT_ROOT/TUFReplay.MicrophoneCapture.Mac/TUFReplayMicrophoneCapture.xcodeproj"

TUFREPLAY_PACKAGE_BUILD_ROOT="${TUFREPLAY_PACKAGE_ROOT:-$TUFREPLAY_PROJECT_ROOT/build/package}"
TUFREPLAY_PACKAGE_STAGE="$TUFREPLAY_PACKAGE_BUILD_ROOT/TUFReplay"
TUFREPLAY_PACKAGE_ZIP_PATH="${TUFREPLAY_PACKAGE_ZIP:-$TUFREPLAY_PROJECT_ROOT/build/TUFReplay.zip}"
TUFREPLAY_VERSION_ASSET_PATH="${TUFREPLAY_VERSION_ASSET:-$TUFREPLAY_PROJECT_ROOT/build/TUFReplay.version}"
TUFREPLAY_CHECKSUM_ASSET_PATH="${TUFREPLAY_CHECKSUM_ASSET:-$TUFREPLAY_PACKAGE_ZIP_PATH.sha256}"
TUFREPLAY_NUGET_PACKAGES_DIR="${NUGET_PACKAGES:-$HOME/.nuget/packages}"
TUFREPLAY_PLATFORM="$(uname -s)"

export TUFREPLAY_PROJECT_ROOT
export ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE
export UNITY_MOD_MANAGER_DLL HARMONY_DLL ADOFAI_IPC_DLL ADOFAI_IPC_BOOTSTRAP_DLL
export ADOFAI_IPC_INFO_JSON ADOFAI_IPC_BOOTSTRAP_LOCK
export TUFREPLAY_BUILD_OUTPUT TUFREPLAY_BOOTSTRAP_BUILD_OUTPUT TUFREPLAY_INSTALL_PATH
export TUFREPLAY_MAC_HELPER_BUILD_OUTPUT TUFREPLAY_MAC_HELPER_DERIVED_DATA
export TUFREPLAY_MAC_HELPER_BUILT_APP TUFREPLAY_MAC_HELPER_APP TUFREPLAY_MAC_HELPER_EXECUTABLE
export TUFREPLAY_MAC_HELPER_XCODE_PROJECT
export TUFREPLAY_PACKAGE_BUILD_ROOT TUFREPLAY_PACKAGE_STAGE TUFREPLAY_PACKAGE_ZIP_PATH
export TUFREPLAY_VERSION_ASSET_PATH TUFREPLAY_CHECKSUM_ASSET_PATH TUFREPLAY_NUGET_PACKAGES_DIR
export TUFREPLAY_PLATFORM

is_macos() {
  [ "$TUFREPLAY_PLATFORM" = "Darwin" ]
}
