//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "level_revision_charts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "path")]
    pub relative_path: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub canonical_chart_hash: Vec<u8>,
    pub chart_hash_version: i64,
    pub artifact_storage_key: String,
    #[sea_orm(unique_key = "path")]
    pub level_revision_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::level_revisions::Entity",
        from = "Column::LevelRevisionId",
        to = "super::level_revisions::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    LevelRevisions,
    #[sea_orm(has_many = "super::run_sessions::Entity")]
    RunSessions,
}

impl Related<super::level_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LevelRevisions.def()
    }
}

impl Related<super::run_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunSessions.def()
    }
}
