//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "level_revisions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "file")]
    pub tuf_level_id: i64,
    #[sea_orm(unique_key = "file")]
    pub tuf_file_id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub canonical_payload_hash: Vec<u8>,
    pub payload_hash_version: i64,
    pub archive_storage_key: String,
    pub source_updated_at: Option<DateTimeWithTimeZone>,
    pub fetched_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::level_revision_charts::Entity")]
    LevelRevisionCharts,
    #[sea_orm(has_many = "super::run_sessions::Entity")]
    RunSessions,
}

impl Related<super::level_revision_charts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LevelRevisionCharts.def()
    }
}

impl Related<super::run_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunSessions.def()
    }
}
