//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "run_sessions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub status: String,
    pub protocol_version: i64,
    pub client_game_version: String,
    pub client_mod_version: String,
    pub tuf_level_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub upload_token_hash: Vec<u8>,
    pub lease_expires_at: DateTimeWithTimeZone,
    pub hard_expires_at: DateTimeWithTimeZone,
    pub sealed_at: Option<DateTimeWithTimeZone>,
    pub level_revision_id: Option<i64>,
    pub level_revision_chart_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub client_tuf_file_id: String,
    #[sea_orm(column_type = "Text")]
    pub client_level_relative_path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::level_revision_charts::Entity",
        from = "Column::LevelRevisionChartId",
        to = "super::level_revision_charts::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    LevelRevisionCharts,
    #[sea_orm(
        belongs_to = "super::level_revisions::Entity",
        from = "Column::LevelRevisionId",
        to = "super::level_revisions::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    LevelRevisions,
    #[sea_orm(has_one = "super::run_submission_records::Entity")]
    RunSubmissionRecords,
}

impl Related<super::level_revision_charts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LevelRevisionCharts.def()
    }
}

impl Related<super::level_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LevelRevisions.def()
    }
}

impl Related<super::run_submission_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunSubmissionRecords.def()
    }
}
