//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "run_submission_records")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub run_session_id: i64,
    pub owner_id: String,
    pub state: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub manifest: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub validation: Option<Json>,
    pub external_pass_id: Option<i64>,
    pub reason: Option<String>,
    pub requested_at: Option<DateTimeWithTimeZone>,
    pub lease_until: Option<DateTimeWithTimeZone>,
    pub lease_owner: Option<Uuid>,
    pub oauth_grant_id: Option<Uuid>,
    pub evidence_expires_at: Option<DateTimeWithTimeZone>,
    pub retry_count: i32,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    pub ingest_released_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::run_sessions::Entity",
        from = "Column::RunSessionId",
        to = "super::run_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RunSessions,
}

impl Related<super::run_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RunSessions.def()
    }
}
